include ../../../makefiles/Build.mk

SUBSYSTEM = pak
MODULE = physfs_lua
MODULE_NAME = PAK_PhysFS_Lua
include ../../../makefiles/Lua_libs.mk
PREREQS = ../binding_common.h ../binding_common.c

include ../../../makefiles/Binding.mk
