include ../../../makefiles/Build.mk

SUBSYSTEM = ttf
MODULE = freetype2_duktape
MODULE_NAME = TTF_FreeType2_Duktape
include ../../../makefiles/Duktape_libs.mk
PREREQS = ../binding_common.h ../binding_common.c

include ../../../makefiles/Binding.mk
