include ../../../makefiles/Build.mk

SUBSYSTEM = mouse
MODULE = sdl2_duktape
MODULE_NAME = Mouse_SDL2_Duktape
include ../../../makefiles/Duktape_libs.mk
PREREQS = ../binding_common.h ../binding_common.c

include ../../../makefiles/Binding.mk
