SUBSYSTEM = texture
MODULE = sdl2_image_lua
MODULE_NAME = Texture_SDL2_image_Lua
include ../../../makefiles/Lua_libs.mk
PREREQS = ../binding_common.h ../binding_common.c

include ../../../makefiles/Binding.mk
