include ../../../makefiles/Build.mk

SUBSYSTEM = abstraction
MODULE = gui_lua
MODULE_NAME = Abstraction_gui_Lua
include ../../../makefiles/Lua_libs.mk
PREREQS = ../gui_binding_common.h ../gui_binding_common.c

include ../../../makefiles/Binding.mk
