#ifndef MTR_PAK_BINDING_COMMON_C
#define MTR_PAK_BINDING_COMMON_C

#include "marathoner/script_func.h"

MTR_SCRIPT_FUNC_I_S1(MTR_SF_PakFunctionSupported, MTR_PakFunctionSupported)
MTR_SCRIPT_FUNC_B_V(MTR_SF_PakInit, MTR_PakInit)
MTR_SCRIPT_FUNC_B_S2(MTR_SF_PakMount, MTR_PakMount)
MTR_SCRIPT_FUNC_B_S1(MTR_SF_PakUnmount, MTR_PakUnmount)
MTR_SCRIPT_FUNC_B_V(MTR_SF_PakQuit, MTR_PakQuit)
MTR_SCRIPT_FUNC_P_V(MTR_SF_PakGetFopen, MTR_PakGetFopen)
MTR_SCRIPT_FUNC_P_V(MTR_SF_PakGetFclose, MTR_PakGetFclose)
MTR_SCRIPT_FUNC_P_V(MTR_SF_PakGetFeof, MTR_PakGetFeof)
MTR_SCRIPT_FUNC_P_V(MTR_SF_PakGetFtell, MTR_PakGetFtell)
MTR_SCRIPT_FUNC_P_V(MTR_SF_PakGetFseek, MTR_PakGetFseek)
MTR_SCRIPT_FUNC_P_V(MTR_SF_PakGetFread, MTR_PakGetFread)
MTR_SCRIPT_FUNC_P_V(MTR_SF_PakGetFwrite, MTR_PakGetFwrite)

void MTR_ScriptsRegisterAll(void)
{
    #ifdef MTR_MOD_PLUGIN
    mtrVm = MTR_ScriptsGetVm();
    #endif

    MTR_FIND_AND_ADD_FUNCTION(MTR_SOURCE_MODULE, PakFunctionSupported);
    MTR_FIND_AND_ADD_FUNCTION(MTR_SOURCE_MODULE, PakInit);
    MTR_FIND_AND_ADD_FUNCTION(MTR_SOURCE_MODULE, PakMount);
    MTR_FIND_AND_ADD_FUNCTION(MTR_SOURCE_MODULE, PakUnmount);
    MTR_FIND_AND_ADD_FUNCTION(MTR_SOURCE_MODULE, PakQuit);
    MTR_FIND_AND_ADD_FUNCTION(MTR_SOURCE_MODULE, PakGetFopen);
    MTR_FIND_AND_ADD_FUNCTION(MTR_SOURCE_MODULE, PakGetFclose);
    MTR_FIND_AND_ADD_FUNCTION(MTR_SOURCE_MODULE, PakGetFeof);
    MTR_FIND_AND_ADD_FUNCTION(MTR_SOURCE_MODULE, PakGetFtell);
    MTR_FIND_AND_ADD_FUNCTION(MTR_SOURCE_MODULE, PakGetFseek);
    MTR_FIND_AND_ADD_FUNCTION(MTR_SOURCE_MODULE, PakGetFread);
    MTR_FIND_AND_ADD_FUNCTION(MTR_SOURCE_MODULE, PakGetFwrite);
}

#endif
