include ../../../makefiles/Build.mk

SUBSYSTEM = utils
MODULE = math_duktape
MODULE_NAME = Utils_math_Duktape
include ../../../makefiles/Duktape_libs.mk
PREREQS = ../math_binding_common.h ../math_binding_common.c

include ../../../makefiles/Binding.mk
