SUBSYSTEM = abstraction
MODULE = sprite_squirrel
MODULE_NAME = Abstraction_sprite_Squirrel
LIBS = -lsquirrel
PREREQS = ../sprite_binding_common.h ../sprite_binding_common.c

include ../../../Binding.mk
