SUBSYSTEM = script
MODULE = lua
MODULE_NAME = Script_Lua
include ../../../makefiles/Lua_libs.mk
PREREQS = ../common.c ../../../include/marathoner/script_func.h
SCRIPT = yes

include ../../../makefiles/Subsystem.mk
