include ../../../makefiles/Build.mk

SUBSYSTEM = ttf
MODULE = sdl2_ttf_duktape
MODULE_NAME = TTF_SDL2_ttf_Duktape
include ../../../makefiles/Duktape_libs.mk
PREREQS = ../binding_common.h ../binding_common.c

include ../../../makefiles/Binding.mk
