include ../../../makefiles/Build.mk

SUBSYSTEM = package
MODULE = physfs_duktape
MODULE_NAME = Package_PhysFS_Duktape
include ../../../makefiles/Duktape_libs.mk
PREREQS = ../binding_common.h ../binding_common.c

include ../../../makefiles/Binding.mk
