SUBSYSTEM = texture
MODULE = sdl2_image_duktape
MODULE_NAME = Texture_SDL2_image_Duktape
ifeq ($(MOD), plugin)
  LIBS = -lduktape.dll
else
  LIBS = -lduktape
endif
PREREQS = ../binding_common.h ../binding_common.c

include ../../../makefiles/Binding.mk
