include ../../../makefiles/Build.mk

SUBSYSTEM = texture
MODULE = sdl2_image_duktape
MODULE_NAME = Texture_SDL2_image_Duktape
include ../../../makefiles/Duktape_libs.mk
PREREQS = ../binding_common.h ../binding_common.c

include ../../../makefiles/Binding.mk
