include ../../../makefiles/Build.mk

SUBSYSTEM = abstraction
MODULE = animated_sprite_duktape
MODULE_NAME = Abstraction_animated_sprite_Duktape
include ../../../makefiles/Duktape_libs.mk
PREREQS = ../animated_sprite_binding_common.h \
 ../animated_sprite_binding_common.c

include ../../../makefiles/Binding.mk
