include ../../../makefiles/Build.mk

SUBSYSTEM = timer
MODULE = emscripten
MODULE_NAME = Timer_Emscripten
LIBS = -s EMTERPRETIFY_WHITELIST=\'[\"_MTR_TimerDelay\"]\'

include ../../../makefiles/Subsystem.mk
