include ../../../makefiles/Build.mk

SUBSYSTEM = json
MODULE = cjson_squirrel
MODULE_NAME = JSON_cJSON_Squirrel
include ../../../makefiles/Squirrel_libs.mk
PREREQS = ../binding_common.h ../binding_common.c

ifeq ($(CROSSPLATFORM), no)
  XINCDIRS = -I/usr/include/squirrel3
endif

include ../../../makefiles/Binding.mk
