include ../../../makefiles/Build.mk

SUBSYSTEM = screen
MODULE = sdl2_duktape
MODULE_NAME = Screen_SDL2_Duktape
include ../../../makefiles/Duktape_libs.mk
PREREQS = ../binding_common.h ../binding_common.c

include ../../../makefiles/Binding.mk
