include ../../../makefiles/Build.mk

SUBSYSTEM = png
MODULE = libpng_duktape
MODULE_NAME = PNG_libpng_Duktape
include ../../../makefiles/Duktape_libs.mk
PREREQS = ../binding_common.h ../binding_common.c

include ../../../makefiles/Binding.mk
