include ../../../makefiles/Build.mk

SUBSYSTEM = package
MODULE = physfs_lua
MODULE_NAME = Package_PhysFS_Lua
include ../../../makefiles/Lua_libs.mk
PREREQS = ../binding_common.h ../binding_common.c

ifeq ($(CROSSPLATFORM), no)
  XINCDIRS = -I/usr/include/lua5.3
endif

include ../../../makefiles/Binding.mk
