include ../../../makefiles/Build.mk

SUBSYSTEM = abstraction
MODULE = sprite_duktape
MODULE_NAME = Abstraction_sprite_Duktape
include ../../../makefiles/Duktape_libs.mk
PREREQS = ../sprite_binding_common.h ../sprite_binding_common.c

include ../../../makefiles/Binding.mk
