include ../../../makefiles/Build.mk

SUBSYSTEM = abstraction
MODULE = gui_duktape
MODULE_NAME = Abstraction_gui_Duktape
include ../../../makefiles/Duktape_libs.mk
PREREQS = ../gui_binding_common.h ../gui_binding_common.c

include ../../../makefiles/Binding.mk
