include ../../../makefiles/Build.mk

SUBSYSTEM = abstraction
MODULE = font_duktape
MODULE_NAME = Abstraction_font_Duktape
include ../../../makefiles/Duktape_libs.mk
PREREQS = ../font_binding_common.h ../font_binding_common.c

include ../../../makefiles/Binding.mk
