SUBSYSTEM = abstraction
MODULE = font_lua
MODULE_NAME = Abstraction_font_Lua
include ../../../makefiles/Lua_libs.mk
PREREQS = ../font_binding_common.h ../font_binding_common.c

include ../../../makefiles/Binding.mk
