include ../../../makefiles/Build.mk

SUBSYSTEM = json
MODULE = cjson_lua
MODULE_NAME = JSON_cJSON_Lua
include ../../../makefiles/Lua_libs.mk
PREREQS = ../binding_common.h ../binding_common.c

include ../../../makefiles/Binding.mk
