include ../../../makefiles/Build.mk

SUBSYSTEM = json
MODULE = cjson_lua
MODULE_NAME = JSON_cJSON_Lua
include ../../../makefiles/Lua_libs.mk
PREREQS = ../binding_common.h ../binding_common.c

ifeq ($(CROSSPLATFORM), no)
  XINCDIRS = -I/usr/include/lua5.3
endif

include ../../../makefiles/Binding.mk
