#ifndef MTR_GAME_CONTROLLER_COMMON
#define MTR_GAME_CONTROLLER_COMMON

#ifdef _SDL_H
    #define MTR_POVHAT_CENTER       SDL_HAT_CENTERED
    #define MTR_POVHAT_UP           SDL_HAT_UP
    #define MTR_POVHAT_DOWN         SDL_HAT_DOWN
    #define MTR_POVHAT_LEFT         SDL_HAT_LEFT
    #define MTR_POVHAT_RIGHT        SDL_HAT_RIGHT
    #define MTR_POVHAT_UP_LEFT      SDL_HAT_LEFTUP
    #define MTR_POVHAT_UP_RIGHT     SDL_HAT_RIGHTUP
    #define MTR_POVHAT_DOWN_LEFT    SDL_HAT_LEFTDOWN
    #define MTR_POVHAT_DOWN_RIGHT   SDL_HAT_RIGHTDOWN
#endif

#endif
