include ../../../makefiles/Build.mk

SUBSYSTEM = timer
MODULE = emscripten_lua
MODULE_NAME = Timer_Emscripten_Lua
include ../../../makefiles/Lua_libs.mk
PREREQS = ../binding_common.h ../binding_common.c

include ../../../makefiles/Binding.mk
