SUBSYSTEM = game_controller
MODULE = sdl2_duktape
MODULE_NAME = Game_Controller_SDL2_Duktape
LIBS = -lduktape.dll
PREREQS = ../binding_common.h ../binding_common.c ../common.h

include ../../../Binding.mk
