include ../../../makefiles/Build.mk

SUBSYSTEM = game_controller
MODULE = sdl2_duktape
MODULE_NAME = Game_Controller_SDL2_Duktape
include ../../../makefiles/Duktape_libs.mk
PREREQS = ../binding_common.h ../binding_common.c

include ../../../makefiles/Binding.mk
