#ifndef MTR_UTILS_MATH_BINDING_COMMON_H
#define MTR_UTILS_MATH_BINDING_COMMON_H

MTR_FUNC(int, MTR_MathFunctionSupported, const char *);
MTR_FUNC(float, MTR_Sin_f, float);
MTR_FUNC(double, MTR_Sin_d, double);
MTR_FUNC(float, MTR_SinFast_f, float);
MTR_FUNC(double, MTR_SinFast_d, double);
MTR_FUNC(float, MTR_Cos_f, float);
MTR_FUNC(double, MTR_Cos_d, double);
MTR_FUNC(float, MTR_CosFast_f, float);
MTR_FUNC(double, MTR_CosFast_d, double);
MTR_FUNC(float, MTR_Tan_f, float);
MTR_FUNC(double, MTR_Tan_d, double);
MTR_FUNC(float, MTR_TanFast_f, float);
MTR_FUNC(double, MTR_TanFast_d, double);
MTR_FUNC(float, MTR_Asin_f, float);
MTR_FUNC(double, MTR_Asin_d, double);
MTR_FUNC(float, MTR_AsinFast_f, float);
MTR_FUNC(double, MTR_AsinFast_d, double);
MTR_FUNC(float, MTR_Acos_f, float);
MTR_FUNC(double, MTR_Acos_d, double);
MTR_FUNC(float, MTR_AcosFast_f, float);
MTR_FUNC(double, MTR_AcosFast_d, double);
MTR_FUNC(float, MTR_Atan_f, float);
MTR_FUNC(double, MTR_Atan_d, double);
MTR_FUNC(float, MTR_AtanFast_f, float);
MTR_FUNC(double, MTR_AtanFast_d, double);
MTR_FUNC(float, MTR_Loge_f, float);
MTR_FUNC(double, MTR_Loge_d, double);
MTR_FUNC(float, MTR_LogeFast_f, float);
MTR_FUNC(double, MTR_LogeFast_d, double);
MTR_FUNC(float, MTR_Log10_f, float);
MTR_FUNC(double, MTR_Log10_d, double);
MTR_FUNC(float, MTR_Log10Fast_f, float);
MTR_FUNC(double, MTR_Log10Fast_d, double);
MTR_FUNC(float, MTR_Log2_f, float);
MTR_FUNC(double, MTR_Log2_d, double);
MTR_FUNC(float, MTR_Log2Fast_f, float);
MTR_FUNC(double, MTR_Log2Fast_d, double);
MTR_FUNC(float, MTR_Log_f, float, float);
MTR_FUNC(double, MTR_Log_d, double, double);
MTR_FUNC(float, MTR_LogFast_f, float, float);
MTR_FUNC(double, MTR_LogFast_d, double, double);
MTR_FUNC(float, MTR_Pow_f, float, float);
MTR_FUNC(double, MTR_Pow_d, double, double);
MTR_FUNC(float, MTR_PowFast_f, float, float);
MTR_FUNC(double, MTR_PowFast_d, double, double);
MTR_FUNC(float, MTR_Sqrt_f, float);
MTR_FUNC(double, MTR_Sqrt_d, double);
MTR_FUNC(float, MTR_SqrtFast_f, float);
MTR_FUNC(double, MTR_SqrtFast_d, double);
MTR_FUNC(float, MTR_Cbrt_f, float);
MTR_FUNC(double, MTR_Cbrt_d, double);
MTR_FUNC(float, MTR_CbrtFast_f, float);
MTR_FUNC(double, MTR_CbrtFast_d, double);
MTR_FUNC(float, MTR_Hypot_f, float, float);
MTR_FUNC(double, MTR_Hypot_d, double, double);
MTR_FUNC(float, MTR_HypotFast_f, float, float);
MTR_FUNC(double, MTR_HypotFast_d, double, double);
MTR_FUNC(float, MTR_Angle_f, float, float);
MTR_FUNC(double, MTR_Angle_d, double, double);
MTR_FUNC(float, MTR_AngleFast_f, float, float);
MTR_FUNC(double, MTR_AngleFast_d, double, double);
MTR_FUNC(float, MTR_Vecx_f, float, float);
MTR_FUNC(double, MTR_Vecx_d, double, double);
MTR_FUNC(float, MTR_VecxFast_f, float, float);
MTR_FUNC(double, MTR_VecxFast_d, double, double);
MTR_FUNC(float, MTR_Vecy_f, float, float);
MTR_FUNC(double, MTR_Vecy_d, double, double);
MTR_FUNC(float, MTR_VecyFast_f, float, float);
MTR_FUNC(double, MTR_VecyFast_d, double, double);
#ifdef lua_h
MTR_FUNC(void, MTR_Vecxy_f, float, float, float *, float *);
MTR_FUNC(void, MTR_Vecxy_d, double, double, double *, double *);
MTR_FUNC(void, MTR_VecxyFast_f, float, float, float *, float *);
MTR_FUNC(void, MTR_VecxyFast_d, double, double, double *, double *);
#endif
MTR_FUNC(int, MTR_Rand, int);
MTR_FUNC(int, MTR_RandRange, int, int);
MTR_FUNC(void, MTR_RandSeed, unsigned int);
MTR_FUNC(void, MTR_RandSeedByTime, void);
MTR_FUNC(int, MTR_Abs, int);
MTR_FUNC(long int, MTR_Abs_l, long int);
MTR_FUNC(long long int, MTR_Abs_ll, long long int);
MTR_FUNC(float, MTR_Abs_f, float);
MTR_FUNC(double, MTR_Abs_d, double);
MTR_FUNC(int, MTR_Sign, int);
MTR_FUNC(long int, MTR_Sign_l, long int);
MTR_FUNC(long long int, MTR_Sign_ll, long long int);
MTR_FUNC(float, MTR_Sign_f, float);
MTR_FUNC(double, MTR_Sign_d, double);
MTR_FUNC(float, MTR_Round_f, float);
MTR_FUNC(double, MTR_Round_d, double);
MTR_FUNC(float, MTR_Floor_f, float);
MTR_FUNC(double, MTR_Floor_d, double);
MTR_FUNC(float, MTR_Ceil_f, float);
MTR_FUNC(double, MTR_Ceil_d, double);
MTR_FUNC(int, MTR_Mod, int, int);
MTR_FUNC(long int, MTR_Mod_l, long int, long int);
MTR_FUNC(long long int, MTR_Mod_ll, long long int, long long int);
MTR_FUNC(float, MTR_Mod_f, float, float);
MTR_FUNC(double, MTR_Mod_d, double, double);
MTR_FUNC(int, MTR_Min, int, int);
MTR_FUNC(long int, MTR_Min_l, long int, long int);
MTR_FUNC(long long int, MTR_Min_ll, long long int, long long int);
MTR_FUNC(float, MTR_Min_f, float, float);
MTR_FUNC(double, MTR_Min_d, double, double);
MTR_FUNC(int, MTR_Max, int, int);
MTR_FUNC(long int, MTR_Max_l, long int, long int);
MTR_FUNC(long long int, MTR_Max_ll, long long int, long long int);
MTR_FUNC(float, MTR_Max_f, float, float);
MTR_FUNC(double, MTR_Max_d, double, double);

#endif
