SUBSYSTEM = utils
MODULE = color_squirrel
MODULE_NAME = Utils_color_Squirrel
LIBS = -lsquirrel
PREREQS = ../color_binding_common.h ../color_binding_common.c ../color_common.h

include ../../../Binding.mk
