#ifndef MTR_MOUSE_COMMON
#define MTR_MOUSE_COMMON

#ifdef _SDL_H
    #define MTR_MOUSE_LEFT   SDL_BUTTON_LEFT
    #define MTR_MOUSE_RIGHT  SDL_BUTTON_RIGHT
    #define MTR_MOUSE_MIDDLE SDL_BUTTON_MIDDLE
    #define MTR_MOUSE_X1     SDL_BUTTON_X1
    #define MTR_MOUSE_X2     SDL_BUTTON_X2
#endif

#endif
