include ../../../makefiles/Build.mk

SUBSYSTEM = audio
MODULE = portaudio_duktape
MODULE_NAME = Audio_PortAudio_Duktape
include ../../../makefiles/Duktape_libs.mk
PREREQS = ../binding_common.h ../binding_common.c ../common.h

include ../../../makefiles/Binding.mk
