include ../../../makefiles/Build.mk

SUBSYSTEM = abstraction
MODULE = scene_duktape
MODULE_NAME = Abstraction_scene_Duktape
include ../../../makefiles/Duktape_libs.mk
PREREQS = ../scene_binding_common.h ../scene_binding_common.c

include ../../../makefiles/Binding.mk
