include ../../../makefiles/Build.mk

SUBSYSTEM = primitive
MODULE = sdl2_gfx_duktape
MODULE_NAME = Primitive_SDL2_gfx_Duktape
include ../../../makefiles/Duktape_libs.mk
PREREQS = ../binding_common.h ../binding_common.c

include ../../../makefiles/Binding.mk
