include ../../../makefiles/Build.mk

SUBSYSTEM = utils
MODULE = math_lua
MODULE_NAME = Utils_math_Lua
include ../../../makefiles/Lua_libs.mk
PREREQS = ../math_binding_common.h ../math_binding_common.c

include ../../../makefiles/Binding.mk
