SUBSYSTEM = primitive
MODULE = sdl2_gfx_lua
MODULE_NAME = Primitive_SDL2_gfx_Lua
include ../../../makefiles/Lua_libs.mk
PREREQS = ../binding_common.h ../binding_common.c

include ../../../makefiles/Binding.mk
