SUBSYSTEM = formats
MODULE = sdl_gpu
MODULE_NAME = Formats_sdl_gpu
LIBS = -lsdl_gpu -lSDL2 -lstb_image -lstb_image_write -lglew32.dll -lopengl32 -lgdi32 -lwinmm -limm32 -lole32 -loleaut32 -lversion

include ../../../Subsystem.mk

