SUBSYSTEM = utils
MODULE = color_duktape
MODULE_NAME = Utils_color_Duktape
LIBS = -lduktape.dll
PREREQS = ../color_binding_common.h ../color_binding_common.c ../color_common.h

include ../../../Binding.mk
