include ../../../makefiles/Build.mk

SUBSYSTEM = timer
MODULE = emscripten_duktape
MODULE_NAME = Timer_Emscripten_Duktape
PREREQS = ../binding_common.h ../binding_common.c

include ../../../makefiles/Binding.mk
