include ../../../makefiles/Build.mk

SUBSYSTEM = ttf
MODULE = freetype2_lua
MODULE_NAME = TTF_FreeType2_Lua
include ../../../makefiles/Lua_libs.mk
PREREQS = ../binding_common.h ../binding_common.c

include ../../../makefiles/Binding.mk
