include ../../../makefiles/Build.mk

SUBSYSTEM = screen
MODULE = sdl2_gpu_lua
MODULE_NAME = Screen_SDL2_gpu_Lua
include ../../../makefiles/Lua_libs.mk
PREREQS = ../binding_common.h ../binding_common.c

include ../../../makefiles/Binding.mk
