include ../../../makefiles/Build.mk

SUBSYSTEM = json
MODULE = cjson_duktape
MODULE_NAME = JSON_cJSON_Duktape
include ../../../makefiles/Duktape_libs.mk
PREREQS = ../binding_common.h ../binding_common.c

include ../../../makefiles/Binding.mk
