include ../../../makefiles/Build.mk

SUBSYSTEM = abstraction
MODULE = animated_sprite_lua
MODULE_NAME = Abstraction_animated_sprite_Lua
include ../../../makefiles/Lua_libs.mk
PREREQS = ../sprite_binding_common.h ../sprite_binding_common.c

include ../../../makefiles/Binding.mk
