include ../../../makefiles/Build.mk

SUBSYSTEM = abstraction
MODULE = scene_lua
MODULE_NAME = Abstraction_scene_Lua
include ../../../makefiles/Lua_libs.mk
PREREQS = ../scene_binding_common.h ../scene_binding_common.c

include ../../../makefiles/Binding.mk
